# Generated by Django 4.1.5 on 2023-02-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('num_weeks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The Player's First Name", max_length=20)),
                ('last_name', models.CharField(help_text="The Player's Last Name", max_length=20)),
                ('pledge_class', models.IntegerField(help_text='Pledge Class Year')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hit', models.IntegerField()),
                ('miss', models.IntegerField()),
                ('dropped', models.IntegerField()),
                ('plink', models.IntegerField()),
                ('plunk', models.IntegerField()),
                ('negative_points', models.IntegerField()),
                ('self_plunk', models.IntegerField()),
                ('kicked', models.IntegerField()),
                ('caught_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caught_by', to='die.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die.game')),
                ('kicked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kicked_by', to='die.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tossed_by', to='die.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBigPointStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
                ('misses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plinks', models.IntegerField(default=0)),
                ('plunks', models.IntegerField(default=0)),
                ('kicks', models.IntegerField(default=0)),
                ('self_plunks', models.IntegerField(default=0)),
                ('negative_points', models.IntegerField(default=0)),
                ('point_number', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die.player')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='die.league')),
                ('players', models.ManyToManyField(to='die.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='big_points',
            field=models.ManyToManyField(related_name='big_point_stats', to='die.playerbigpointstats'),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='die.league'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='die.leagueteam'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_1_player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team11', to='die.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_1_player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team12', to='die.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='die.leagueteam'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2_player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team21', to='die.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2_player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team22', to='die.player'),
        ),
    ]
