# Generated by Django 4.1.5 on 2023-02-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0002_playerbigpointstats_catches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='big_points',
        ),
        migrations.AddField(
            model_name='playerbigpointstats',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='die.game'),
            preserve_default=False,
        ),
    ]
