# Generated by Django 4.1.5 on 2023-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0003_remove_game_big_points_playerbigpointstats_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
