# Generated by Django 4.1.5 on 2023-02-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0004_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='toss',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
