# Generated by Django 4.1.5 on 2023-02-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0006_alter_game_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['pledge_class', 'last_name', 'first_name']},
        ),
    ]
