# Generated by Django 4.1.5 on 2023-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('die', '0007_alter_player_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='locked',
            field=models.IntegerField(default=0),
        ),
    ]
